version: '3'
services:
  pg:
      image: postgres:latest
      container_name: pg_db
      environment:
        - POSTGRES_USER=${DB_USER}  
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - DATABASE_HOST=${DB_HOST} 
      ports:
        - '5432:5432'
      volumes:
        - database_postgres:/var/lib/postgresql/data
      networks:
        - fullstack
      healthcheck:
        test: pg_isready -U postgres

  go:
    container_name: go_app
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      pg:
        condition: service_healthy          
    networks:
      - fullstack

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge